-- Crear el usuario Developer 1 (gestiona reservas y mesas)
CREATE USER DEVELOPER1 IDENTIFIED BY soyJhoan2025;
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO DEVELOPER1;
GRANT CREATE SESSION TO DEVELOPER1;
GRANT CREATE TABLE TO DEVELOPER1;
GRANT CREATE VIEW TO DEVELOPER1;
GRANT CREATE PROCEDURE TO DEVELOPER1;
GRANT CREATE TRIGGER TO DEVELOPER1;
GRANT CREATE SEQUENCE TO DEVELOPER1;
GRANT CREATE JOB TO DEVELOPER1;
GRANT UNLIMITED TABLESPACE TO DEVELOPER1;
GRANT CREATE PUBLIC SYNONYM TO DEVELOPER1;
GRANT SELECT ON ALL_SYNONYMS TO DEVELOPER1;

-- Crear el usuario Developer 2 (gestiona ventas y productos)
CREATE USER DEVELOPER2 IDENTIFIED BY soyAngie2025;
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO DEVELOPER2;
GRANT CREATE SESSION TO DEVELOPER2;
GRANT CREATE TABLE TO DEVELOPER2;
GRANT CREATE VIEW TO DEVELOPER2;
GRANT CREATE PROCEDURE TO DEVELOPER2;
GRANT CREATE SEQUENCE TO DEVELOPER2;
GRANT CREATE JOB TO DEVELOPER2;
GRANT UNLIMITED TABLESPACE TO DEVELOPER2;
GRANT CREATE PUBLIC SYNONYM TO DEVELOPER2;
GRANT SELECT ON ALL_SYNONYMS TO DEVELOPER2;


SELECT * FROM DEVELOPER2.ORDER_STATUS_TYPE;
SELECT * FROM DEVELOPER2.PAYMENT_TYPE;
SELECT * FROM DEVELOPER2.CATEGORY;
SELECT * FROM DEVELOPER2.PRODUCT;


SELECT * FROM DEVELOPER1.RESTAURANT_TABLE;
SELECT * FROM DEVELOPER1.RESTAURANT_USER;
SELECT * FROM DEVELOPER1.USER_TYPE;